version: 2.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - run:
          name: Run tests
          command: ./gradlew test --info

  semgrep-scan:
    parameters:
      default_branch:
        type: string
        default: main
    environment:

    docker:
      - image: returntocorp/semgrep:develop
        user: root
    working_directory: /src
    steps:
      - checkout
      - run:
          name: "Semgrep scan"
          command: semgrep ci


workflows:
  test-deploy:
    jobs:
      - test
      - semgrep-scan
