version: 2.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - run:
          name: Run tests
          command: ./gradlew test --info

workflows:
  test-deploy:
    jobs:
      - test
