version: 2.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:11.0.1
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Run tests
          command: ./gradlew test --info
      - run: ./gradlew clean build
      - store_artifacts:
          path: build/reports/checkstyle
          destination: checkstyle


workflows:
  test-deploy:
    jobs:
      - test
