version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0.12

    environment:
      JVM_OPTS: -Xmx3200m
  test:
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - run:
          name: Run tests
          command: ./gradlew test --info
      - run: ./gradlew clean build
      - store_artifacts:
          path: build/reports/checkstyle
          destination: checkstyle

workflows:
  test-deploy:
    jobs:
      - test
